/**
 * POST /api/generate
 *
 * Accepts an OpenAPI spec + project metadata and returns a ZIP archive
 * containing a complete Next.js project scaffold with the generated
 * route handlers, interfaces, Zod schemas, middlewares and services
 * overlaid on top inside `src/`.
 *
 * This runs entirely server-side so we can use Node fs/path safely.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { PassThrough } from 'node:stream';

import archiver from 'archiver';
import { NextRequest, NextResponse } from 'next/server';

import { writeSiteExportToProject } from '@/lib/generateSiteExport';
import type { UIPage } from '@/types/project';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface GeneratePayload {
  spec: Record<string, unknown>;
  projectName: string;
  middlewares?: {
    name: string;
    code: string;
    enabled: boolean;
    scope: 'global' | 'route';
  }[];
  services?: {
    name: string;
    code?: string;
    dependencies?: { name: string; version: string }[];
    healthCheck?: {
      enabled: boolean;
      path: string;
      code: string;
    };
  }[];
  dataStorage?: {
    provider: string;
    connectionString: string;
    enabled: boolean;
  };
  /** Frontend pages (Swaggen canvas + legacy) for `/site` static export */
  pages?: UIPage[];
  /** Full project JSON for reference / re-import (optional) */
  projectSnapshot?: unknown;
}

interface GeneratedFile {
  path: string;
  content: string;
}

/* ------------------------------------------------------------------ */
/*  Next.js project scaffold                                           */
/* ------------------------------------------------------------------ */

/**
 * Write a minimal but complete Next.js (App Router, TypeScript) project
 * scaffold into `projectDir`. All swaggen-generated files are overlaid
 * on top afterwards inside `src/`.
 */
function scaffoldNextProject(projectDir: string, projectName: string) {
  const write = (rel: string, content: string) => {
    const full = path.join(projectDir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  };

  // package.json — includes zod which the generated schemas need
  write(
    'package.json',
    JSON.stringify(
      {
        name: projectName.toLowerCase().replace(/\s+/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: '^15.0.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          zod: '^3.23.0',
        },
        devDependencies: {
          '@types/node': '^20',
          '@types/react': '^19',
          '@types/react-dom': '^19',
          typescript: '^5',
        },
      },
      null,
      2,
    ),
  );

  // tsconfig.json
  write(
    'tsconfig.json',
    JSON.stringify(
      {
        compilerOptions: {
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          baseUrl: '.',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./src/*'] },
        },
        include: [
          'next-env.d.ts',
          '**/*.ts',
          '**/*.tsx',
          '**/*.json',
          '.next/types/**/*.ts',
        ],
        exclude: ['node_modules'],
      },
      null,
      2,
    ),
  );

  // next.config.ts
  write(
    'next.config.ts',
    `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {};

export default nextConfig;
`,
  );

  // .gitignore
  write(
    '.gitignore',
    [
      '# Next.js',
      '.next/',
      'out/',
      '',
      '# Node',
      'node_modules/',
      '',
      '# Env',
      '.env*.local',
      '',
      '# Misc',
      '.DS_Store',
      '*.pem',
    ].join('\n'),
  );

  // README.md
  write(
    'README.md',
    `# ${projectName}

Generated by [swaggen](https://github.com/your-org/swaggen).

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.
`,
  );

  // src/app/layout.tsx
  write(
    'src/app/layout.tsx',
    `import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by swaggen',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  );

  // src/app/page.tsx
  write(
    'src/app/page.tsx',
    `export default function Home() {
  return (
    <main>
      <h1>${projectName}</h1>
      <p>Generated by swaggen.</p>
    </main>
  );
}
`,
  );
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/** Recursively read all files under `dir`, returning relative paths + content. */
function readDirRecursive(dir: string, base: string = dir): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  if (!fs.existsSync(dir)) return files;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...readDirRecursive(full, base));
    } else {
      files.push({
        path: path.relative(base, full),
        content: fs.readFileSync(full, 'utf-8'),
      });
    }
  }
  return files;
}

/** Remove a directory and all its contents. */
function cleanup(dir: string) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * Collect all generated files from `projectDir` into a ZIP archive and
 * resolve with the Buffer. The archive preserves the full folder structure
 * so the download extracts as a ready-to-use Next.js project.
 */
function buildZipBuffer(projectDir: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const passThrough = new PassThrough();

    passThrough.on('data', (chunk: Buffer) => chunks.push(chunk));
    passThrough.on('end', () => resolve(Buffer.concat(chunks)));
    passThrough.on('error', reject);

    const archive = archiver('zip', { zlib: { level: 6 } });
    archive.on('error', reject);
    archive.pipe(passThrough);

    // Add the entire project directory, preserving folder structure
    archive.directory(projectDir, false);

    archive.finalize();
  });
}

/**
 * In-process spec-to-code generator.
 * Writes all generated files under `outDir` which maps to `src/` inside the
 * scaffolded Next.js project. Route handlers land in `src/app/api/…`,
 * interfaces in `src/interfaces/`, etc.
 */
function generateFromSpec(
  spec: Record<string, unknown>,
  outDir: string,
  middlewarePayload?: GeneratePayload['middlewares'],
  servicesPayload?: GeneratePayload['services'],
) {
  const filesWritten: string[] = [];

  const schemas = ((spec.components as Record<string, unknown>)?.schemas ??
    {}) as Record<string, Record<string, unknown>>;

  const paths = (spec.paths ?? {}) as Record<string, Record<string, unknown>>;

  // 1. Generate TypeScript interfaces
  const interfacesDir = path.join(outDir, 'interfaces');
  fs.mkdirSync(interfacesDir, { recursive: true });
  const interfaceNames: string[] = [];

  for (const [name, schema] of Object.entries(schemas)) {
    interfaceNames.push(name);
    const content = buildInterface(name, schema);
    const filePath = path.join(interfacesDir, `${name}.ts`);
    fs.writeFileSync(filePath, content, 'utf-8');
    filesWritten.push(filePath);
  }

  // Barrel export for interfaces
  const ifBarrel = interfaceNames
    .map(n => `export type { ${n} } from './${n}';`)
    .join('\n');
  const ifBarrelPath = path.join(interfacesDir, 'index.ts');
  fs.writeFileSync(ifBarrelPath, `// Auto-generated\n${ifBarrel}\n`, 'utf-8');
  filesWritten.push(ifBarrelPath);

  // 2. Generate Zod schemas
  const validationDir = path.join(outDir, 'validation');
  fs.mkdirSync(validationDir, { recursive: true });
  const zodNames: string[] = [];

  for (const [name, schema] of Object.entries(schemas)) {
    zodNames.push(`${name}Schema`);
    const content = buildZodSchema(name, schema);
    const filePath = path.join(validationDir, `${name}Schema.ts`);
    fs.writeFileSync(filePath, content, 'utf-8');
    filesWritten.push(filePath);
  }

  const zodBarrel = zodNames
    .map(n => `export { ${n} } from './${n}';`)
    .join('\n');
  const zodBarrelPath = path.join(validationDir, 'index.ts');
  fs.writeFileSync(zodBarrelPath, `// Auto-generated\n${zodBarrel}\n`, 'utf-8');
  filesWritten.push(zodBarrelPath);

  // 3. Generate route handlers — placed under src/app/api/
  const routesDir = path.join(outDir, 'app', 'api');
  for (const [apiPath, methods] of Object.entries(paths)) {
    const folderPath = apiPath
      .split('/')
      .filter(Boolean)
      .map(seg =>
        seg.startsWith('{') && seg.endsWith('}')
          ? `[${seg.slice(1, -1)}]`
          : seg,
      )
      .join('/');

    const routeDir = path.join(routesDir, folderPath);
    fs.mkdirSync(routeDir, { recursive: true });

    const content = buildRouteFile(apiPath, methods);
    const routePath = path.join(routeDir, 'route.ts');
    fs.writeFileSync(routePath, content, 'utf-8');
    filesWritten.push(routePath);
  }

  // 4. Generate middleware utility helpers under src/lib/
  const libDir = path.join(outDir, 'lib');
  fs.mkdirSync(libDir, { recursive: true });
  fs.writeFileSync(
    path.join(libDir, 'middleware.ts'),
    MIDDLEWARE_TEMPLATE,
    'utf-8',
  );
  fs.writeFileSync(
    path.join(libDir, 'validation.ts'),
    VALIDATION_TEMPLATE,
    'utf-8',
  );
  fs.writeFileSync(
    path.join(libDir, 'baseService.ts'),
    BASE_SERVICE_TEMPLATE,
    'utf-8',
  );
  filesWritten.push(
    path.join(libDir, 'middleware.ts'),
    path.join(libDir, 'validation.ts'),
    path.join(libDir, 'baseService.ts'),
  );

  // 5. Generate middleware files under src/middlewares/
  const mwDir = path.join(outDir, 'middlewares');
  fs.mkdirSync(mwDir, { recursive: true });
  const allMiddlewareNames: string[] = [];

  // 5a. User-authored middleware code (from the UI)
  const enabledMws = (middlewarePayload ?? []).filter(m => m.enabled);
  for (const mw of enabledMws) {
    allMiddlewareNames.push(mw.name);
    fs.writeFileSync(path.join(mwDir, `${mw.name}.ts`), mw.code, 'utf-8');
    filesWritten.push(path.join(mwDir, `${mw.name}.ts`));
  }

  // 5b. Placeholders for spec-referenced middlewares not covered above
  const specMiddlewareNames = collectMiddlewareNames(paths);
  const coveredNames = new Set(allMiddlewareNames);
  for (const mwName of specMiddlewareNames) {
    if (!coveredNames.has(mwName)) {
      allMiddlewareNames.push(mwName);
      const mwContent = buildMiddlewarePlaceholder(mwName);
      fs.writeFileSync(path.join(mwDir, `${mwName}.ts`), mwContent, 'utf-8');
      filesWritten.push(path.join(mwDir, `${mwName}.ts`));
    }
  }

  // 5c. Barrel export
  if (allMiddlewareNames.length > 0) {
    const barrel = allMiddlewareNames
      .map(n => `export { ${n} } from './${n}';`)
      .join('\n');
    const barrelPath = path.join(mwDir, 'index.ts');
    fs.writeFileSync(barrelPath, `// Auto-generated\n${barrel}\n`, 'utf-8');
    filesWritten.push(barrelPath);
  }

  // 5d. Next.js middleware.ts entrypoint for global middlewares — lives at src/
  const globalMws = enabledMws.filter(m => m.scope === 'global');
  if (globalMws.length > 0) {
    const entrypoint = buildGlobalMiddlewareEntrypoint(globalMws);
    const entrypointPath = path.join(outDir, 'middleware.ts');
    fs.writeFileSync(entrypointPath, entrypoint, 'utf-8');
    filesWritten.push(entrypointPath);
  }

  // 6. Generate service class files under src/services/
  const allServices = servicesPayload ?? [];
  const namedServices = allServices.filter(s => s.name);

  if (namedServices.length > 0) {
    const servicesDir = path.join(outDir, 'services');
    fs.mkdirSync(servicesDir, { recursive: true });

    for (const svc of namedServices) {
      const fileContent = svc.code || buildDefaultServiceClass(svc.name);
      const fileName = `${svc.name}.ts`;
      fs.writeFileSync(path.join(servicesDir, fileName), fileContent, 'utf-8');
      filesWritten.push(path.join(servicesDir, fileName));
    }

    // Barrel export
    const barrel = namedServices
      .map(s => `export * from './${s.name}';`)
      .join('\n');
    fs.writeFileSync(
      path.join(servicesDir, 'index.ts'),
      `// Auto-generated\n${barrel}\n`,
      'utf-8',
    );
    filesWritten.push(path.join(servicesDir, 'index.ts'));
  }

  // 6b. Collect external service dependencies → package.json fragment
  const allDeps: Record<string, string> = {};
  for (const svc of namedServices) {
    for (const dep of svc.dependencies ?? []) {
      if (dep.name) allDeps[dep.name] = dep.version || 'latest';
    }
  }
  if (Object.keys(allDeps).length > 0) {
    const depsContent = JSON.stringify({ dependencies: allDeps }, null, 2);
    fs.writeFileSync(
      path.join(outDir, 'service-dependencies.json'),
      depsContent,
      'utf-8',
    );
    filesWritten.push(path.join(outDir, 'service-dependencies.json'));
  }

  // 6c. Aggregated health route for all named services
  if (namedServices.length > 0) {
    const healthRoute = buildAggregatedHealthRoute(
      namedServices.map(s => s.name),
    );
    const healthRouteDir = path.join(outDir, 'app', 'api', 'health');
    fs.mkdirSync(healthRouteDir, { recursive: true });
    fs.writeFileSync(
      path.join(healthRouteDir, 'route.ts'),
      healthRoute,
      'utf-8',
    );
    filesWritten.push(path.join(healthRouteDir, 'route.ts'));
  }

  return {
    filesWritten,
    interfacesCount: interfaceNames.length,
    schemasCount: zodNames.length,
    routesCount: Object.keys(paths).length,
  };
}

/* ------------------------------------------------------------------ */
/*  Code generation helpers                                            */
/* ------------------------------------------------------------------ */

function buildInterface(name: string, schema: Record<string, unknown>): string {
  const props = (schema.properties ?? {}) as Record<
    string,
    Record<string, unknown>
  >;
  const required = new Set((schema.required ?? []) as string[]);
  const lines = [
    `// Auto-generated from OpenAPI spec`,
    `export interface ${name} {`,
  ];

  for (const [propName, propSchema] of Object.entries(props)) {
    const tsType = jsonToTsType(propSchema);
    const opt = required.has(propName) ? '' : '?';
    if (propSchema.description)
      lines.push(`  /** ${propSchema.description} */`);
    lines.push(`  ${propName}${opt}: ${tsType};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

function jsonToTsType(schema: Record<string, unknown>): string {
  if (schema.$ref) {
    const parts = (schema.$ref as string).split('/');
    return parts[parts.length - 1];
  }
  if (schema.type === 'array') {
    const items = schema.items as Record<string, unknown> | undefined;
    return items ? `${jsonToTsType(items)}[]` : 'unknown[]';
  }
  if (schema.enum) {
    return (schema.enum as string[]).map(v => `'${v}'`).join(' | ');
  }

  const typeMap: Record<string, string> = {
    string: 'string',
    number: 'number',
    integer: 'number',
    boolean: 'boolean',
    object: 'Record<string, unknown>',
  };
  return typeMap[(schema.type as string) ?? 'string'] ?? 'unknown';
}

function buildZodSchema(name: string, schema: Record<string, unknown>): string {
  const props = (schema.properties ?? {}) as Record<
    string,
    Record<string, unknown>
  >;
  const required = new Set((schema.required ?? []) as string[]);

  const fields = Object.entries(props)
    .map(([propName, propSchema]) => {
      const zodType = jsonToZodType(propSchema);
      const opt = required.has(propName) ? '' : '.optional()';
      return `  ${propName}: ${zodType}${opt},`;
    })
    .join('\n');

  return [
    `// Auto-generated from OpenAPI spec`,
    `import { z } from 'zod';`,
    '',
    `export const ${name}Schema = z.object({`,
    fields,
    `});`,
    '',
    `export type ${name} = z.infer<typeof ${name}Schema>;`,
    '',
  ].join('\n');
}

function jsonToZodType(schema: Record<string, unknown>): string {
  if (schema.$ref) {
    const parts = (schema.$ref as string).split('/');
    return `${parts[parts.length - 1]}Schema`;
  }
  if (schema.type === 'array') {
    const items = schema.items as Record<string, unknown> | undefined;
    return items ? `z.array(${jsonToZodType(items)})` : 'z.array(z.unknown())';
  }
  if (schema.enum) {
    const values = (schema.enum as string[]).map(v => `'${v}'`).join(', ');
    return `z.enum([${values}])`;
  }

  const typeMap: Record<string, string> = {
    string: 'z.string()',
    number: 'z.number()',
    integer: 'z.number().int()',
    boolean: 'z.boolean()',
    object: 'z.record(z.unknown())',
  };
  const base = typeMap[(schema.type as string) ?? 'string'] ?? 'z.unknown()';

  if (schema.format === 'uuid') return 'z.string().uuid()';
  if (schema.format === 'date-time') return 'z.string().datetime()';
  if (schema.format === 'email') return 'z.string().email()';

  return base;
}

function buildRouteFile(
  apiPath: string,
  methods: Record<string, unknown>,
): string {
  const lines = [
    `// Auto-generated route handler for ${apiPath}`,
    `import { NextRequest, NextResponse } from 'next/server';`,
    '',
  ];

  const httpMethods = ['get', 'post', 'put', 'patch', 'delete'];
  for (const method of httpMethods) {
    const op = methods[method] as Record<string, unknown> | undefined;
    if (!op) continue;

    const fnName = method.toUpperCase();
    const operationId = (op.operationId as string) ?? `${method}Handler`;

    lines.push(`/** ${op.summary ?? operationId} */`);
    lines.push(`export async function ${fnName}(req: NextRequest) {`);
    lines.push(`  // TODO: implement ${operationId}`);
    lines.push(
      `  return NextResponse.json({ message: '${operationId} not implemented' }, { status: 501 });`,
    );
    lines.push(`}`);
    lines.push('');
  }

  return lines.join('\n');
}

function collectMiddlewareNames(
  paths: Record<string, Record<string, unknown>>,
): string[] {
  const names = new Set<string>();
  for (const methods of Object.values(paths)) {
    for (const op of Object.values(methods)) {
      const opObj = op as Record<string, unknown>;
      const mws = opObj['x-middlewares'] as string[] | undefined;
      if (mws) mws.forEach(m => names.add(m));
    }
  }
  return Array.from(names);
}

function buildMiddlewarePlaceholder(name: string): string {
  return [
    `// Auto-generated middleware placeholder: ${name}`,
    `import { NextRequest, NextResponse } from 'next/server';`,
    `import type { PipelineContext, SwaggenMiddlewareResult } from '../lib/middleware';`,
    '',
    `export async function ${name}(`,
    `  req: NextRequest,`,
    `  ctx: PipelineContext,`,
    `): Promise<SwaggenMiddlewareResult> {`,
    `  // TODO: implement ${name} middleware logic`,
    `  return {};`,
    `}`,
    '',
  ].join('\n');
}

function buildGlobalMiddlewareEntrypoint(
  globalMws: { name: string; scope: string }[],
): string {
  const imports = globalMws
    .map(mw => `import { ${mw.name} } from './middlewares/${mw.name}';`)
    .join('\n');

  const chain = globalMws.map(mw => `  ${mw.name},`).join('\n');

  return `// Auto-generated Next.js middleware entrypoint
import { NextRequest, NextResponse } from 'next/server';

${imports}
import { createPipelineContext, mergeContext } from './lib/middleware';

const globalMiddlewares = [
${chain}
];

export async function middleware(req: NextRequest) {
  const ctx = createPipelineContext();

  for (const mw of globalMiddlewares) {
    try {
      const result = await mw(req, ctx);
      if (result.response) return result.response;
      mergeContext(ctx, result.ctx);
    } catch (error) {
      console.error(\`[middleware] \${mw.name} failed:\`, error);
      return NextResponse.json(
        { error: 'Internal middleware error' },
        { status: 500 },
      );
    }
  }

  const response = NextResponse.next();

  if (ctx.corsHeaders) {
    for (const [key, value] of Object.entries(ctx.corsHeaders)) {
      response.headers.set(key, value);
    }
  }
  if (ctx.requestId) {
    response.headers.set('x-request-id', ctx.requestId);
  }

  return response;
}

export const config = {
  matcher: ['/api/:path*'],
};
`;
}

function buildDefaultServiceClass(name: string): string {
  const varName = name[0].toLowerCase() + name.slice(1);
  return `import { BaseService, type HealthCheckResult } from '../lib/baseService';

export class ${name} extends BaseService {
  readonly serviceName = '${name}';

  async healthCheck(): Promise<HealthCheckResult> {
    return this.health(async () => {
      // Add dependency checks here (DB, cache, third-party APIs, etc.)
      return this.ok({ ready: true });
    });
  }
}

export const ${varName} = new ${name}();
`;
}

function buildAggregatedHealthRoute(serviceNames: string[]): string {
  const imports = serviceNames
    .map(name => {
      const varName = name[0].toLowerCase() + name.slice(1);
      return `import { ${varName} } from '../../../services/${name}';`;
    })
    .join('\n');

  const instances = serviceNames
    .map(name => `  ${name[0].toLowerCase()}${name.slice(1)}`)
    .join(',\n');

  return `// Auto-generated aggregated health endpoint
import { NextResponse } from 'next/server';

${imports}

const services = [
${instances},
];

export async function GET() {
  const results = await Promise.allSettled(
    services.map(svc => svc.healthCheck()),
  );

  const checks = results.map((r, i) => {
    if (r.status === 'fulfilled') return r.value;
    return {
      service: services[i].serviceName,
      healthy: false,
      details: { error: (r.reason as Error)?.message ?? 'Unknown error' },
    };
  });

  const allHealthy = checks.every(c => c.healthy);

  return NextResponse.json(
    { healthy: allHealthy, services: checks },
    { status: allHealthy ? 200 : 503 },
  );
}
`;
}

/* ------------------------------------------------------------------ */
/*  Templates                                                          */
/* ------------------------------------------------------------------ */

const MIDDLEWARE_TEMPLATE = `import { NextRequest, NextResponse } from 'next/server';

export interface PipelineContext {
  requestId?: string;
  requestStart?: number;
  userId?: string;
  token?: string;
  validatedBody?: unknown;
  corsHeaders?: Record<string, string>;
  custom: Record<string, unknown>;
}

export interface SwaggenMiddlewareResult {
  response?: NextResponse;
  ctx?: Partial<Omit<PipelineContext, 'custom'>> & {
    custom?: Record<string, unknown>;
  };
}

export type SwaggenMiddleware = (
  req: NextRequest,
  ctx: PipelineContext,
) => Promise<SwaggenMiddlewareResult>;

export function createPipelineContext(): PipelineContext {
  return { custom: {} };
}

export function mergeContext(
  ctx: PipelineContext,
  partial?: SwaggenMiddlewareResult['ctx'],
): void {
  if (!partial) return;
  const { custom, ...rest } = partial;
  Object.assign(ctx, rest);
  if (custom) Object.assign(ctx.custom, custom);
}

export async function withMiddlewares(
  req: NextRequest,
  middlewares: SwaggenMiddleware[],
  handler: (req: NextRequest, ctx: PipelineContext) => Promise<NextResponse>,
): Promise<NextResponse> {
  const ctx = createPipelineContext();

  try {
    for (const mw of middlewares) {
      const result = await mw(req, ctx);
      if (result.response) return result.response;
      mergeContext(ctx, result.ctx);
    }
    return await handler(req, ctx);
  } catch (err) {
    const requestId = ctx.requestId ?? 'unknown';
    const message = err instanceof Error ? err.message : 'Internal server error';
    console.error(\`[error] \${req.method} \${req.nextUrl.pathname} [\${requestId}]\`, err);
    return NextResponse.json(
      { error: 'Internal server error', requestId, message },
      { status: 500 },
    );
  }
}
`;

const VALIDATION_TEMPLATE = `import { NextRequest, NextResponse } from 'next/server';
import { ZodSchema } from 'zod';

export async function validateRequest<T>(
  req: NextRequest,
  schema: ZodSchema<T>,
): Promise<{ data: T; error?: undefined } | { data?: undefined; error: NextResponse }> {
  try {
    const body = await req.json();
    const data = schema.parse(body);
    return { data };
  } catch (err) {
    return {
      error: NextResponse.json(
        { error: 'Validation failed', details: (err as Error).message },
        { status: 400 },
      ),
    };
  }
}
`;

const BASE_SERVICE_TEMPLATE = `export interface HealthCheckResult {
  service: string;
  healthy: boolean;
  details?: Record<string, unknown>;
}

export class ServiceError extends Error {
  readonly code: string;
  readonly status: number;
  readonly details?: Record<string, unknown>;

  constructor(
    message: string,
    options?: {
      code?: string;
      status?: number;
      details?: Record<string, unknown>;
      cause?: unknown;
    },
  ) {
    super(message);
    this.name = 'ServiceError';
    this.code = options?.code ?? 'SERVICE_ERROR';
    this.status = options?.status ?? 500;
    this.details = {
      ...(options?.details ?? {}),
      ...(options?.cause !== undefined ? { cause: String(options.cause) } : {}),
    };
  }
}

export abstract class BaseService {
  abstract readonly serviceName: string;

  abstract healthCheck(): Promise<HealthCheckResult>;

  protected log(level: 'debug' | 'info' | 'warn' | 'error', ...args: unknown[]) {
    const prefix = \`[service:\${this.serviceName}]\`;
    const fn = level === 'error'
      ? console.error
      : level === 'warn'
      ? console.warn
      : level === 'debug'
      ? console.debug
      : console.log;
    fn(prefix, ...args);
  }

  protected healthy(details?: Record<string, unknown>): HealthCheckResult {
    return { service: this.serviceName, healthy: true, ...(details ? { details } : {}) };
  }

  protected unhealthy(details?: Record<string, unknown>): HealthCheckResult {
    return { service: this.serviceName, healthy: false, ...(details ? { details } : {}) };
  }

  /** Alias for clearer health-check call sites. */
  protected ok(details?: Record<string, unknown>): HealthCheckResult {
    return this.healthy(details);
  }

  /** Alias for clearer health-check call sites. */
  protected fail(details?: Record<string, unknown>): HealthCheckResult {
    return this.unhealthy(details);
  }

  /**
   * Wrap service operations with uniform error mapping + logging.
   * Useful for route handlers or higher-level orchestration.
   */
  protected async execute<T>(
    operation: string,
    fn: () => Promise<T>,
  ): Promise<T> {
    const startedAt = Date.now();
    try {
      const result = await fn();
      this.log('debug', operation, 'ok', \`\${Date.now() - startedAt}ms\`);
      return result;
    } catch (err) {
      const mapped = this.toServiceError(err);
      this.log('error', operation, mapped.code, mapped.message, mapped.details);
      throw mapped;
    }
  }

  /**
   * Wrap health checks so they never throw (they should always return a result).
   */
  protected async health(
    check: () => Promise<HealthCheckResult>,
  ): Promise<HealthCheckResult> {
    try {
      return await check();
    } catch (err) {
      const mapped = this.toServiceError(err);
      return this.fail({ code: mapped.code, error: mapped.message, ...mapped.details });
    }
  }

  protected requireEnv(name: string): string {
    const env = (globalThis as { process?: { env?: Record<string, string | undefined> } })
      .process?.env;
    const value = env?.[name];
    if (!value) {
      throw new ServiceError(\`Missing required env var: \${name}\`, {
        code: 'MISSING_ENV',
        status: 500,
        details: { env: name },
      });
    }
    return value;
  }

  protected toServiceError(err: unknown): ServiceError {
    if (err instanceof ServiceError) return err;
    if (err instanceof Error) {
      return new ServiceError(err.message, {
        code: 'UNEXPECTED_ERROR',
        status: 500,
        details: { name: err.name },
      });
    }
    return new ServiceError('Unknown service error', {
      code: 'UNKNOWN_ERROR',
      status: 500,
      details: { raw: String(err) },
    });
  }
}
`;

/* ------------------------------------------------------------------ */
/*  Route handler                                                      */
/* ------------------------------------------------------------------ */

export async function POST(req: NextRequest) {
  let tmpDir: string | null = null;

  try {
    const payload: GeneratePayload = await req.json();

    if (!payload.spec) {
      return NextResponse.json(
        { error: 'Missing "spec" in request body' },
        { status: 400 },
      );
    }

    const projectSlug = (payload.projectName || 'my-app')
      .toLowerCase()
      .replace(/\s+/g, '-');

    // 1. Create temp directory
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'swaggen-'));

    // 2. Scaffold a full Next.js project structure at the root
    const projectDir = path.join(tmpDir, projectSlug);
    fs.mkdirSync(projectDir, { recursive: true });
    scaffoldNextProject(projectDir, payload.projectName || 'My App');

    // 3. Overlay generated files into src/ so they sit inside the project
    const srcDir = path.join(projectDir, 'src');
    fs.mkdirSync(srcDir, { recursive: true });

    const result = generateFromSpec(
      payload.spec,
      srcDir,
      payload.middlewares,
      payload.services,
    );

    writeSiteExportToProject(projectDir, {
      pages: payload.pages ?? [],
      projectSnapshot: payload.projectSnapshot,
      projectName: payload.projectName || 'My App',
    });

    // 4. Read generated file list for the response metadata (before zipping)
    const generatedFiles = readDirRecursive(srcDir, projectDir);

    // 5. Build ZIP archive of the entire project directory
    const zipBuffer = await buildZipBuffer(projectDir);

    return new NextResponse(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${projectSlug}.zip"`,
        'X-Files-Count': String(generatedFiles.length),
        'X-Interfaces-Count': String(result.interfacesCount),
        'X-Schemas-Count': String(result.schemasCount),
        'X-Routes-Count': String(result.routesCount),
      },
    });
  } catch (e) {
    console.error('Generation failed:', e);
    return NextResponse.json({ error: (e as Error).message }, { status: 500 });
  } finally {
    if (tmpDir) cleanup(tmpDir);
  }
}
